### ISSUE TITLE
"^_[^A-Z\u0000-\u0020]+$" is not suitable for a <Tag> of <DataItems>

### ISSUE THREAD

**Issue by SofiaXu** [COMCIFS/CIF_JSON#4]
Hello!

I have checked cif 1.1 spec and 2.0 spec and found that Upper Chars are included in char set for <Tag>.

refer:
https://www.iucr.org/resources/cif/spec/version1.1/cifsyntax
https://www.iucr.org/__data/assets/text_file/0009/112131/CIF2-ENBF.txt

**Comment by wojdyr** [comment]
Yes, CIF tags are case-insensitive. In CIF-JSON they are normalized to lower case.

**Comment by jcbollinger** [comment]
Yes, CIF allows uppercase letters in tag names, and always has done.  But it is *case insensitive*, as Marcin observed.  That has a slightly broader meaning in CIF 2.0, with its wider character repertoire, than it does in CIF 1.1.

Among the aims of CIF-JSON is to reduce processing requirements for CIF-JSON consumers.  To this end, CIF-JSON requires tag names (and data block names and save frame names) to be presented in a normalized form.  This is covered in [the prose version of the CIF-JSON spec](https://github.com/COMCIFS/CIF_JSON/blob/main/README.md), in item (2) of the "Encoding and character set requirements" section:

> All names used for CIF data block headers, CIF data names, and CIF save block headers must be represented in CIF-JSON in Unicode case-normal form (also referred to as “lower-case” below), and otherwise conform to the characterset restrictions of the CIF2 syntax.

Converting tag names to that form has no semantic implications whatever, and requiring them to be presented in that form relieves consumers from having to deal with CIF's case-insensitivity.  CIF-JSON is not intended to be able to represent semantically insignificant details such as the case of characters in tag names.

**Comment by jcbollinger** [comment]
Closing.

**Comment by wojdyr** [comment]
A quick question. I tried googling *Unicode case-normal form*, but haven't found a good reference. Is it a well-known term? I found description of *Unicode normalization forms*, but didn't manage to find "case-normal".

**Comment by jcbollinger** [comment]
> A quick question. I tried googling _Unicode case-normal form_, but haven't found a good reference. Is it a well-known term? I found description of _Unicode normalization forms_, but didn't manage to find "case-normal".

I'm not sure any more exactly where that particular term came from. Odd. But it refers to the name equivalence criterion in the CIF 2.0 specifications, which is that names are equivalent if they are Unicode *canonical caseless matches* of each other.  That term is defined in the Unicode specifications.  The case-normal form is intended to be understood as the form that is compared for testing canonical caseless matching, which is the result of

 1. converting to Unicode normalization form NFD, then
 2. applying the Unicode `toCaseFold` algorithm to the result, and finally
 3. converting the folded result to Unicode normalization form NFD (which is not necessarily a no-op)

For names that contain only ASCII characters, the same result can be obtained simply by lowercasing all the letters within.
